# Generated by Django 3.1.2 on 2020-12-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internfair', '0003_auto_20201215_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='transactionId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
