# Generated by Django 3.1.2 on 2020-12-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0004_auto_20201215_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_form',
            name='FormStatus',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVE', 'DEACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='intern_form',
            name='allowances',
            field=models.CharField(blank=True, default='N/A', max_length=150),
        ),
        migrations.AlterField(
            model_name='intern_form',
            name='remarks',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='intern_form',
            name='stipend',
            field=models.CharField(blank=True, default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('REJECTED', 'rejected'), ('SHORTLISTED', 'shortlisted'), ('PENDING', 'pending')], default='PENDING', max_length=20),
        ),
    ]
