# Generated by Django 3.1.2 on 2020-12-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0006_auto_20201225_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='internapplication',
            name='Intern_contact',
            field=models.CharField(default='not submitted', max_length=100),
        ),
        migrations.AddField(
            model_name='internapplication',
            name='Intern_email',
            field=models.CharField(default='not submitted', max_length=100),
        ),
        migrations.AddField(
            model_name='internapplication',
            name='Intern_name',
            field=models.CharField(default='not submitted', max_length=100),
        ),
        migrations.AddField(
            model_name='internapplication',
            name='Startup_name',
            field=models.CharField(default='not submitted', max_length=100),
        ),
        migrations.AddField(
            model_name='internapplication',
            name='Startup_profile',
            field=models.CharField(default='not submitted', max_length=100),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('REJECTED', 'rejected'), ('SHORTLISTED', 'shortlisted'), ('PENDING', 'pending')], default='PENDING', max_length=20),
        ),
    ]
