# Generated by Django 3.1.2 on 2020-12-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0007_auto_20201225_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('REJECTED', 'rejected'), ('SHORTLISTED', 'shortlisted')], default='PENDING', max_length=20),
        ),
    ]
