# Generated by Django 3.1.2 on 2020-12-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0008_auto_20201225_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intern_form',
            name='FormStatus',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DEACTIVE', 'DEACTIVE')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='intern_form',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intern_form',
            name='profile',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='intern_form',
            name='questions',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='intern_form',
            name='stipend',
            field=models.CharField(blank=True, default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='internapplication',
            name='Status',
            field=models.CharField(choices=[('REJECTED', 'rejected'), ('PENDING', 'pending'), ('SHORTLISTED', 'shortlisted')], default='PENDING', max_length=20),
        ),
    ]
